// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjLgPYO1Pk_WD5qNte2XDpAVn4YZ3Kdco',
    appId: '1:182790068407:web:100b3f893707720b3a5532',
    messagingSenderId: '182790068407',
    projectId: 'bookswap-app-faa15',
    authDomain: 'bookswap-app-faa15.firebaseapp.com',
    storageBucket: 'bookswap-app-faa15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpJK5SmO2ZEz2301rrZslsaUg5UNJQULE',
    appId: '1:182790068407:android:a6c803e6ce9ab9273a5532',
    messagingSenderId: '182790068407',
    projectId: 'bookswap-app-faa15',
    storageBucket: 'bookswap-app-faa15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzxKA0rog7_Z-_Bvj1b5JpHTHfffc4H0A',
    appId: '1:182790068407:ios:885e9febbb3522c83a5532',
    messagingSenderId: '182790068407',
    projectId: 'bookswap-app-faa15',
    storageBucket: 'bookswap-app-faa15.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzxKA0rog7_Z-_Bvj1b5JpHTHfffc4H0A',
    appId: '1:182790068407:ios:885e9febbb3522c83a5532',
    messagingSenderId: '182790068407',
    projectId: 'bookswap-app-faa15',
    storageBucket: 'bookswap-app-faa15.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjLgPYO1Pk_WD5qNte2XDpAVn4YZ3Kdco',
    appId: '1:182790068407:web:383ce6a5e8ffb2993a5532',
    messagingSenderId: '182790068407',
    projectId: 'bookswap-app-faa15',
    authDomain: 'bookswap-app-faa15.firebaseapp.com',
    storageBucket: 'bookswap-app-faa15.firebasestorage.app',
  );
}
